# Generated by Django 5.0.2 on 2024-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210926_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
