# Generated by Django 5.0.2 on 2024-05-30 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeedetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='joiningdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
