# Generated by Django 5.0.2 on 2024-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeedetail_status_document_signedcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOC_PENDING', 'Document Pending'), ('DOC_VERIFIED', 'Document Verified'), ('CONTRACT_PENDING', 'Contract Pending'), ('FINALIZED', 'Finalized')], default='PENDING', max_length=25),
        ),
    ]
