# Generated by Django 5.0.2 on 2024-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_document_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='blood_group',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='tehsil',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
