# Generated by Django 5.0.2 on 2024-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employeedetail_empcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='empcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
