# Generated by Django 5.0.2 on 2024-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employeedetail_empcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='employee_string',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
