# Generated by Django 5.0.2 on 2024-06-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employeedetail_employee_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='employee_string',
        ),
    ]
