# Generated by Django 5.0.2 on 2024-06-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_remove_employeedetail_employee_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
