# Generated by Django 5.0.2 on 2024-06-04 17:55

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employeedetail_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='expiry_date',
            field=models.DateField(default=employee.models.default_expiry_date),
        ),
    ]
