# Generated by Django 5.0.2 on 2024-06-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employeedetail_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='coverage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
