# Generated by Django 5.0.2 on 2024-06-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employeedetail_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
