# Generated by Django 5.0.2 on 2024-06-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_signedcontract_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
